### ISSUE TITLE
Use github template if it's available

### ISSUE THREAD

**Issue by david-gero-cp** [balvig/cp8_cli#27]
👋 ,

I was wondering to add GitHub template to the new PR would be a good idea.

If I know well, we can use the `template` parameter when we open a new PR.

What do you think? 

https://help.github.com/articles/about-automation-for-issues-and-pull-requests-with-query-parameters/

**Comment by balvig** [comment]
Aha, I guess currently `cp8_cli` _overrides_ any template, as it sets the `body` automatically: https://github.com/cookpad/cp8_cli/blob/master/test/main_test.rb#L42

The main purpose of that is the convenience of getting an automatic reference to a related issue, ie:

```
Closes balvig/cp8_cli#I43
```

I _think_ if we specify a `template` we can't also have custom body text, butI wonder if there would a way to "mix" the two by dynamically appending the body, of I suppose `cp8_cli` could maybe also "manually" read the contents of a template.md and merge the two together?

**Comment by david-gero-cp** [comment]
Yes, you are right. I also had the concern about it. 

I tried it and it overwrites the template. However, it's possible that the GitHub doesn't support the template via API. Maybe it's just the GitHub enterprise function. 

Anyway, currently, the body will overwrite the template.

```bash
curl -X POST --user "USERNAME" https://api.github.com/repos/USERNAME/REPO/pulls --data '{"title": "test_title", "head": "REPO:BRANCH", "base": "master", "body": "testing body message", "template": "pull_request_template.md"}' -H "X-GitHub-OTP: OTP"
```

I'm going to close it. Thank you!

**Comment by david-gero-cp** [comment]
Oh, sorry, I forget to response the idea. 

It's a good idea. It's possible to load the template file from the `.github` folder and add the reference to the top of it and send it as the body.
