### ISSUE TITLE
open doesn't work on Linux

### ISSUE THREAD

**Issue by radeklat** [balvig/cp8_cli#47]
The `cp8 open` command uses the `open` command, which is implemented only on macOS. On other systems it fails. On Linux, `xdg-open <URL>` can be used. Or maybe there is a cross platform solution for Ruby already.

https://github.com/cookpad/cp8_cli/blob/master/lib/cp8_cli/command.rb#L17

**Comment by benhowes** [comment]
Looks like `OS.open_file_command` from https://github.com/rdp/os would be a good way to go
